version: "3"
services:
  starknet:
    image: ghcr.io/dojoengine/dojo:latest
    command: katana
    networks:
      - faucet
    # Hack while dojo merges a working HEALTCHECK
    healthcheck:
      test: echo "ok"
      start_period: 3s

  starkcet-back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      starknet:
        condition: service_healthy
    environment:
      - PRIVATE_KEY=0x0300001800000000300000180000000000030000000000003006001800006600
      - STARKNET_ACCOUNT_ADDRESS=0x03ee9e18edc71a6df30ac3aca2e0b02a198fbce19b7480a63a0d71cbd76652e0
      - TOKEN_ADDRESS=0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7
      - RPC_URL=http://starknet:5050
      - AMOUNT_TRANSFERED=1000000000000000
      - KAKAROT_ADDRESS=0x3968af0316b34e2fa30cee5f222d52e817d6183adc910699a641cd9c7eaea2
    ports:
      - 4000:4000
    networks:
      - faucet

  starkcet-front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - starkcet-back
    networks:
      - faucet

networks:
  faucet:
